name: Github Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: make install

      - name: Test
        run: make test

      - name: Lint
        run: make lint
