name: Github Actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: make setup

      - name: Test
        run: make test

      - name: Lint
        run: make lint
